Components/CartSummaryViewComponent.cs
using cah264_mission09.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cah264_mission09.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket bask;
        public CartSummaryViewComponent(Basket cartService)
        {
            bask = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(bask);
        }
    }
}

Views/Shared/BookstoreSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
        </h4>
    </div>

    <!--Animated blook ovals bounce in-->
    <div class="badge badge-pill badge-primary animate__animated animate__bounceIn">

        <ul>
            <li>Author: @Model.Author</li>
            <li>Category: @Model.Category</li>
            <li>Classification: @Model.Classification</li>
            <li>PageCount: @Model.PageCount</li>
            <li>Publisher: @Model.Publisher</li>
            <li>Isbn: @Model.Isbn</li>
            <li>Price: @Model.Price</li>
        </ul>

    </div>

    <!-- form to push the quantity and bookId that you want to buy to the BookShelf Page-->
    <form method="post" asp-page="/BookShelf">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <div class="input-group">
            <input type="number" class="form-control" name="quantity" value="1" min="1">
            <button type="submit" class="btn btn-success" data-toggle="tooltip" title="Click me!">Purchase</button>
        </div>

    </form>


    @*<div class="card-text p-1">@b.Description</div>*@
</div>

<!--        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Purchase</button>
        </span>-->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cah264_mission09</title>
    <link href="/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <!--Both columns, the categories and the main info split between the two pages-->
    @*<div class="bg-dark text-white p-2 col-12">
        <span class="navbar-brand m-lg-2">Bookstore</span>
        <div class="bg-dark text-white p-2 col-1 offset-md-11">
            <vc:cart-summary />
        </div>
    </div>*@

    <div class="bg-dark text-white p-2">
        <div class="row">
            <div class="col-lg-11" style="font-size: 28px;">
                Bookstore
            </div>
            <div class="col-lg-1 text-lg-end">
                <vc:cart-summary />
            </div>
        </div>
    </div>


    <div class="row m-1 p-1">

        <div id="categories" class="col-3">
            <vc:Category></vc:Category>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>

    </div>
</body>
</html>