Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using cah264_mission09.Models;

namespace cah264_mission09.Controllers
{
    public class CartController : Controller
    {
        private ICartRepository repo { get; set; }
        private Basket basket { get; set; }

        public CartController(ICartRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Order());
        }
         
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                order.Lines = basket.Items.ToArray();
                repo.SaveOrder(order);
                basket.ClearBasket();

                return RedirectToPage("/OrderCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/BookShelf.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using cah264_mission09.Infrastructure;
using cah264_mission09.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace cah264_mission09.Pages
{
    public class BookShelfModel : PageModel
    {

        private IBookstoreRepository repo { get; set; }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        public BookShelfModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        
        public IActionResult OnPost(int bookId, string returnUrl, int quantity)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, quantity);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
         
        public IActionResult OnPostRemove(int orderId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == orderId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Pages/OrderCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace cah264_mission09.Pages
{
    public class OrderCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/BookShelf.cshtml
@page
@model cah264_mission09.Pages.BookShelfModel
@{
}

<h2>Your basket</h2>
<div class="container-fluid row justify-content-center">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Item</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var i in Model.basket.Items)
            {
                <tr>
                    <td>@i.Book.Title</td>
                    <td>@i.Quantity</td>
                    <td>@i.Price</td>
                    <td>@((i.Quantity * i.Price).ToString("c"))</td>

                    <td class="text-center">
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="orderId" value="@i.Book.BookId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

        <tfoot>
            <tr>
                <td colspan="3">Total:</td>
                <td>@Model.basket.CalculateTotal().ToString("c")</td>
            </tr>
        </tfoot>
    </table>

    <div>
        <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Buying</a>
        <a class="btn btn-primary" asp-controller="Cart" asp-action="Checkout">Checkout</a>
    </div>
</div>

Pages/OrderCompleted.cshtml
@page
@model cah264_mission09.Pages.OrderCompletedModel
@{
}
<div class="text-center">
    <h2>Thanks! Your order will be there soon!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Pages/_BookShelfLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        BookShelf - Checkout
    </div>

    <div class="mt-1">
        @RenderBody()
    </div>
</body>
</html>